TTC_RNG,US,call=33,timer=414,caller=80383cc4,object=8034af08,slot=92,list=2,behavior=800ee2f4,action=0,objectTimer=17,ttcSpeed=0,seedBefore=66a4,seedAfter=b2b1,return=b2b1,marioParticleFlags=00000001,marioActiveParticles=00000001,frame=F
TTC_RNG,US,call=34,timer=414,caller=80383cc4,object=8034ffc8,slot=126,list=8,behavior=800ed65c,action=0,objectTimer=0,ttcSpeed=0,seedBefore=b2b1,seedAfter=2630,return=2630,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F
TTC_RNG,US,call=35,timer=414,caller=80383cc4,object=8034ffc8,slot=126,list=8,behavior=800ed65c,action=0,objectTimer=0,ttcSpeed=0,seedBefore=2630,seedAfter=f84f,return=f84f,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F
TTC_RNG,US,call=36,timer=414,caller=80383cc4,object=80350228,slot=127,list=12,behavior=800ed680,action=0,objectTimer=0,ttcSpeed=0,seedBefore=f84f,seedAfter=5994,return=5994,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F
TTC_RNG,US,call=37,timer=414,caller=80383cc4,object=80350228,slot=127,list=12,behavior=800ed680,action=0,objectTimer=0,ttcSpeed=0,seedBefore=5994,seedAfter=34f2,return=34f2,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F
TTC_RNG,US,call=38,timer=415,caller=80383cc4,object=8034af08,slot=92,list=2,behavior=800ee2f4,action=0,objectTimer=18,ttcSpeed=0,seedBefore=34f2,seedAfter=99e5,return=99e5,marioParticleFlags=00000001,marioActiveParticles=00000001,frame=F+1
TTC_RNG,US,call=39,timer=415,caller=80383cc4,object=80350488,slot=128,list=8,behavior=800ed65c,action=0,objectTimer=0,ttcSpeed=0,seedBefore=99e5,seedAfter=922f,return=922f,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F+1
TTC_RNG,US,call=40,timer=415,caller=80383cc4,object=80350488,slot=128,list=8,behavior=800ed65c,action=0,objectTimer=0,ttcSpeed=0,seedBefore=922f,seedAfter=69f1,return=69f1,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F+1
TTC_RNG,US,call=41,timer=415,caller=80383cc4,object=803506e8,slot=129,list=12,behavior=800ed680,action=0,objectTimer=0,ttcSpeed=0,seedBefore=69f1,seedAfter=9849,return=9849,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F+1
TTC_RNG,US,call=42,timer=415,caller=80383cc4,object=803506e8,slot=129,list=12,behavior=800ed680,action=0,objectTimer=0,ttcSpeed=0,seedBefore=9849,seedAfter=5aa1,return=5aa1,marioParticleFlags=00000001,marioActiveParticles=00000000,frame=F+1
