(** Generic projection and global-environment transport for a successful
    CompCert [make_program].  Keeping these dependent-elimination lemmas in a
    small module prevents each concrete target receipt from rechecking them. *)

From Coq Require Import List.
From compcert Require Import AST Clight Coqlib Ctypes Errors Globalenvs Maps.

(** The dependent match generated by CompCert's [Program Definition]
    [make_program] is difficult to eliminate after its scrutinee has already
    been specialized.  This is the same match with that scrutinee exposed as
    a variable. *)
Definition make_program_from_build_result
    (types : list composite_definition)
    (definitions : list (ident * globdef Clight.fundef type))
    (public : list ident) (main : ident)
    (result : res composite_env)
    (Hresult : result = build_composite_env types) : res Clight.program :=
  match result as observed
    return observed = build_composite_env types -> res Clight.program
  with
  | OK composite_environment => fun Hcomposites =>
      OK {| prog_defs := definitions;
            prog_public := public;
            prog_main := main;
            prog_types := types;
            prog_comp_env := composite_environment;
            prog_comp_env_eq :=
              Ctypes.make_program_obligation_1 types Hcomposites |}
  | Error error => fun _ => Error error
  end Hresult.

Lemma make_program_from_build_result_success_definitions :
  forall (types : list composite_definition)
      (definitions : list (ident * globdef Clight.fundef type))
      (public : list ident) (main : ident)
      (result : res composite_env)
      (Hresult : result = build_composite_env types)
      (program : Clight.program),
    make_program_from_build_result types definitions public main
      result Hresult = OK program ->
    prog_defs program = definitions.
Proof.
  intros types definitions public main result Hresult program Hmake.
  destruct result as [composite_environment | error].
  - simpl in Hmake. inversion Hmake. reflexivity.
  - discriminate.
Qed.

(** A successful [make_program] retains its input definition list exactly. *)
Lemma make_program_success_definitions :
  forall (types : list composite_definition)
      (definitions : list (ident * globdef Clight.fundef type))
      (public : list ident) (main : ident) (program : Clight.program),
    Ctypes.make_program types definitions public main = OK program ->
    prog_defs program = definitions.
Proof.
  intros types definitions public main program Hmake.
  eapply make_program_from_build_result_success_definitions
    with (result := build_composite_env types)
         (Hresult := eq_refl).
  exact Hmake.
Qed.

(** Selecting the successful program from a [res] preserves the input
    definitions without first materializing an equality between a large
    concrete [make_program] result and its selected fallback wrapper. *)
Lemma successful_result_selected_program_definitions :
  forall (types : list composite_definition)
      (definitions : list (ident * globdef Clight.fundef type))
      (public : list ident) (main : ident) (fallback : Clight.program)
      (result : res Clight.program),
    result = Ctypes.make_program types definitions public main ->
    (match result with OK _ => true | Error _ => false end) = true ->
    prog_defs
      (match result with OK program => program | Error _ => fallback end) =
      definitions.
Proof.
  intros types definitions public main fallback result Hresult Hsuccess.
  destruct result as [program | error].
  - cbn. eapply make_program_success_definitions.
    symmetry. exact Hresult.
  - discriminate.
Qed.

Definition select_successful_program
    (result : res Clight.program) (fallback : Clight.program) : Clight.program :=
  match result with OK program => program | Error _ => fallback end.

Definition program_result_succeeds (result : res Clight.program) : bool :=
  match result with OK _ => true | Error _ => false end.

Lemma selected_successful_program_definitions :
  forall (types : list composite_definition)
      (definitions : list (ident * globdef Clight.fundef type))
      (public : list ident) (main : ident) (fallback : Clight.program)
      (result : res Clight.program),
    result = Ctypes.make_program types definitions public main ->
    program_result_succeeds result = true ->
    prog_defs (select_successful_program result fallback) = definitions.
Proof.
  intros types definitions public main fallback result Hresult Hsuccess.
  unfold program_result_succeeds in Hsuccess.
  unfold select_successful_program.
  eapply successful_result_selected_program_definitions.
  - exact Hresult.
  - exact Hsuccess.
Qed.

(** Exact definitions plus name uniqueness suffice for global-environment
    resolution, independently of how the enclosing program was built. *)
Lemma program_definitions_resolve_internal_globalenv :
  forall (program : Clight.program)
      (definitions : list (ident * globdef Clight.fundef type))
      (id : ident) (body : Clight.function),
    prog_defs program = definitions ->
    list_norepet (map fst definitions) ->
    In (id, Gfun (Internal body)) definitions ->
    exists block,
      Genv.find_symbol (Clight.globalenv program) id = Some block /\
      Genv.find_funct_ptr (Clight.globalenv program) block =
        Some (Internal body).
Proof.
  intros program definitions id body Hdefs Hunique Hdefinition.
  assert (Hdefmap :
    (prog_defmap program) ! id = Some (Gfun (Internal body))).
  {
    eapply prog_defmap_norepet.
    - change (list_norepet (map fst (prog_defs program))).
      now rewrite Hdefs.
    - change (In (id, Gfun (Internal body)) (prog_defs program)).
      now rewrite Hdefs.
  }
  apply (proj1 (Genv.find_def_symbol program id
    (Gfun (Internal body)))) in Hdefmap.
  destruct Hdefmap as [block [Hsymbol Hbody]].
  exists block. split; [exact Hsymbol |].
  apply Genv.find_funct_ptr_iff. exact Hbody.
Qed.

(** A unique internal definition supplied to a successful [make_program]
    resolves to the same body in the resulting global environment. *)
Lemma successful_make_program_resolves_internal_globalenv :
  forall (types : list composite_definition)
      (definitions : list (ident * globdef Clight.fundef type))
      (public : list ident) (main : ident) (program : Clight.program)
      (id : ident) (body : Clight.function),
    Ctypes.make_program types definitions public main = OK program ->
    list_norepet (map fst definitions) ->
    In (id, Gfun (Internal body)) definitions ->
    exists block,
      Genv.find_symbol (Clight.globalenv program) id = Some block /\
      Genv.find_funct_ptr (Clight.globalenv program) block =
        Some (Internal body).
Proof.
  intros types definitions public main program id body
    Hmake Hunique Hdefinition.
  pose proof (make_program_success_definitions
    types definitions public main program Hmake) as Hdefs.
  eapply program_definitions_resolve_internal_globalenv.
  - exact Hdefs.
  - exact Hunique.
  - exact Hdefinition.
Qed.
